apiVersion: apps/v1
kind: Deployment
metadata:
  name: maprando-web-stable
  labels:
    app: maprando-web-stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maprando-web-stable
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: maprando-web-stable
    spec:
      affinity:
        podAntiAffinity:                                 
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:                               
              matchLabels:                               
                app: maprando-web-stable
      containers:
      - name: maprando-web-stable
        image: docker.io/bkerby/map-rando:v118b
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        args:
        - "--seed-repository-url"
        - "s3:map-rando-seeds"
        - "--video-storage-url"
        - "https://map-rando-videos.b-cdn.net"
        resources:
          requests:
            cpu: 200m
            memory: 2G
          limits:
            memory: 2G
        volumeMounts:
        - name: gcp-key
          mountPath: "/data/gcp"
          readOnly: true
        env:
        - name: AWS_ENDPOINT
          value: https://s3.us-west-004.backblazeb2.com
        - name: AWS_ACCESS_KEY_ID
          value: "00489874733cab00000000007"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: maprando-seeds-backblaze
              key: application-key
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: gcp-key
        secret:
          secretName: gcloud-storage
      
---

apiVersion: v1
kind: Service
metadata:
  name: maprando-web-stable
spec:
  selector:
    app: maprando-web-stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
