# For situations where we need to re-encode everything in bulk, this can temporarily turned up.
# This uses a separate RabbitMQ queue ("bulk-encoding-tasks") to avoid interfering with the usual video encoding
# that happens when videos are uploaded.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-encoder-bulk
  labels:
    app: video-encoder-bulk
spec:
  replicas: 0
  selector:
    matchLabels:
      app: video-encoder-bulk
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: video-encoder-bulk
    spec:
      containers:
      - name: video-encoder
        image: docker.io/bkerby/map-rando-videos:main
        imagePullPolicy: Always
        command: ["/bin/video-encoder"]
        env:
        - name: POSTGRES_HOST
          value: postgres.default.svc.cluster.local
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: RABBIT_URL
          value: amqp://rabbitmq.default.svc.cluster.local/%2f
        - name: RABBIT_QUEUE
          value: bulk-encoding-tasks
        - name: VIDEO_STORAGE_BUCKET_URL
          value: s3:map-rando-videos
        - name: VIDEO_STORAGE_PREFIX
          value: ""
        - name: VIDEO_STORAGE_CLIENT_URL
          value: https://map-rando-videos.s3.us-west-004.backblazeb2.com
        - name: AWS_ENDPOINT
          value: https://s3.us-west-004.backblazeb2.com
        - name: AWS_ACCESS_KEY_ID
          value: "00489874733cab00000000001"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: video-storage-secret
              key: key
        - name: FFMPEG_PATH
          value: "/usr/bin/ffmpeg"
        resources:
          requests:
            cpu: 20m
            memory: 500M
          limits:
            memory: 500M
      volumes:
      - name: video-storage-secret
        secret:
          secretName: video-storage-secret
