apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: blkerby@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - dns01:
        cloudDNS:
          project: super-metroid-map-randomizer
          hostedZoneName: 'maprando-com'
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: blkerby@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        cloudDNS:
          project: super-metroid-map-randomizer
          hostedZoneName: 'maprando-com'
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
