apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: videos-ingress
spec:
  tls:
  - hosts:
    - videos.maprando.com
    secretName: videos-maprando-com-tls
  rules:
  - host: videos.maprando.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: videos
            port:
              number: 80
